version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: perdekj
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - buildernet
  spring-cyran:
    image: jperdek/cyran-back-end
    networks:
      - buildernet
    links:
      - db:db
      - cyran-smtp:cyran-smtp
    build:
      context: ./cyran-back-end
      dockerfile: Dockerfile
    environment:
      DB_PASS: perdekj
      DB_PORT: 5432
      DB_USER: postgres
      DB_HOST: db
      MAIL_HOST: cyran-smtp
    ports:
      - "8080:8080"
    container_name: cyran-back-end
    depends_on:
      - "db"
      - "cyran-smtp"
  security-eshop:
    image: jperdek/cyran-front-end
    build:
      context: ./cyran-front-end
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: cyran-front-end
    depends_on:
      - spring-cyran
  cyran-smtp:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:1025:1025"
      - "8025:8025"
    networks:
      - buildernet
networks:
  buildernet:
    driver: "bridge"
 
